services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 5672:5672 # port for the daemon API
    - 15672:15672 # port for the RabbitMQ management interface
    networks:
      - k8s-project-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  consumer:
    build: consumer
    env_file:
      - .env
    links:
    - rabbitmq
    depends_on:
      rabbitmq:
        condition:
            service_healthy
    ports:
      - "9422:9422"
    networks:
      - k8s-project-network

  producer:
    build: producer
    env_file:
      - .env
    links:
    - rabbitmq
    depends_on:
      rabbitmq:
        condition:
          service_healthy
    networks:
      - k8s-project-network

networks:
  k8s-project-network:
    driver: bridge

volumes:
  rabbitmq_data: