apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: k8s-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-mq
          image: devopsmichaelrosenbaum/consumer:0.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: consumer-config
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: RABBITMQ_PASSWORD
          ports:
            - containerPort: 9422
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"