apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.consumer.replicas }}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-mq
          image: {{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          ports:
            - containerPort: {{ .Values.config.rabbitmq.prometheusPort | int }}
          resources:
            requests:
              cpu: "{{ .Values.consumer.resources.requests.cpu }}"
              memory: "{{ .Values.consumer.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.consumer.resources.limits.cpu }}"
              memory: "{{ .Values.consumer.resources.limits.memory }}"