apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consumer.metricsService.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: {{ .Values.consumer.metricsService.port }}
      targetPort: {{ .Values.consumer.metricsService.port }}
      nodePort: {{ .Values.consumer.metricsService.nodePort }}
  type: NodePort