   services:
     jenkins:
       build:
         context: .
         args:
           DOCKER_GID: 20  # Pass Docker GID (modify this to match your system)
       container_name: jenkins
       ports:
         - "8080:8080"
         - "50000:50000"
       volumes:
         - jenkins_home:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock
       environment:
         - DOCKER_HOST=tcp://dind:2375
       depends_on:
         - dind
       restart: unless-stopped
       networks:
         - shared_network
         - dind_network

     dind:
       image: docker:20.10-dind
       container_name: dind
       privileged: true
       environment:
         - DOCKER_TLS_CERTDIR=
       volumes:
         - dind_storage:/var/lib/docker
       networks:
         - dind_network

   volumes:
     jenkins_home:
     dind_storage:

   networks:
     shared_network:
       external: true
     dind_network:
       driver: bridge