pipeline {
    agent any
    options {
        buildDiscarder(logRotator(daysToKeepStr: '5', numToKeepStr: '5'))
    }
    environment {
        // The `PYTHONPATH` environment variable points to the Jenkins workspace root
        PYTHONPATH = "${env.WORKSPACE}"

        // Dynamic build-related variables
        DOCKER_TAG = "${env.BUILD_NUMBER}"

        // Docker repository and image names
        DOCKER_REPO_NAME = "devopsmichaelrosenbaum"
        DOCKER_IMAGE_NAME = "projectdevops"
    }
    stages {
        stage('checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/devopsMR/k8s-project.git'
            }
        }
    }
    post {
        failure {
            script {
            }
        }
    }
}

