pipeline {
    agent any
    options {
        buildDiscarder(logRotator(daysToKeepStr: '5', numToKeepStr: '5'))
    }
    environment {
        PYTHONPATH = "${env.WORKSPACE}"
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        DOCKER_REPO_NAME = "devopsmichaelrosenbaum"
        DOCKER_IMAGE_NAME = "projectdevops"
    }
    stages {
        stage('checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/devopsMR/k8s-project.git'
            }
        }
    }
    post {
        failure {
            script {
                // Add actions you want upon job failure, like:
                echo "Build failed! Please check the logs for more details."
            }
        }
    }
}