apiVersion: v1
kind: Service
metadata:
  name: consumer-metrics-service
  namespace: k8s-project
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 9422
      targetPort: 9422
      nodePort: 30007
  type: NodePort

  # minikube service consumer-metrics-service -n k8s-project --url